# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: go-example.yml
env:
  FILE_NAME: 'hello-server'

on:
  push:
    branches: [ "main" ]
  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    with:
      path: ./{{ env.FILE_NAME }}
    
